export const DICIPLINAS = [
    {
        id:'0001',
        name: 'Adriano Anunciação Oliveira',
        disabled:false,
        hours:0,
    },  
    {
        id:'0002',
        name: 'Alysson Diniz dos Santos',
        disabled:false,
        hours:0,
    }, 
    {
        id:'0003',
        name: 'Andrea Pinheiro Paiva Cavalcante',
        disabled:false,
        hours:0,
    }, 
    {
        id:'0004',
        name: 'Andrei Bosco Bezerra Torres ',
        disabled:false,
        hours:0,
    }, 
    {
        id:'0005',
        name: 'Antônio José Melo Leite Júnior',
        disabled:false,
        hours:0,
    },    
    {
        id:'0006',
        name: 'Carlos Diego Andrade de Almeida',
        disabled:false,
        hours:0,
    },
    {
        id:'0007',
        name: 'Carlos Eduardo Brito Novais',
        disabled:false,
        hours:0,
    },
    {
        id:'0008',
        name: 'Cátia Luzia Oliveira da Silva',
        disabled:false,
        hours:0,
    },
    {
        id:'0009',
        name: 'Clemilson Costa dos Santos',
        disabled:false,
        hours:0,
    },
    {
        id:'0010',
        name: 'Edgar Marçal de Barros Filho',
        disabled:false,
        hours:0,
    },
    {
        id:'0011',
        name: 'Eduardo Santos Junqueira Rodrigues',
        disabled:false,
        hours:0,
    },
    {
        id:'0012',
        name: 'Ernesto Trajano de Lima',
        disabled:false,
        hours:0,
    },
    {
        id:'0013',
        name: 'Fernando Lincoln Carneiro Leão Mattos',
        disabled:false,
        hours:0,
    },
    {
        id:'0014',
        name: 'Francisco Herbert Lima Vasconcelos',
        disabled:false,
        hours:0,
    },
    {
        id:'0015',
        name: 'Gabriel Antoine Louis Paillard',
        disabled:false,
        hours:0,
    },
    {
        id:'0016',
        name: 'Glaudiney Moreira Mendonça Junior',
        disabled:false,
        hours:0,
    },
    {
        id:'0017',
        name: 'George Allan Menezes Gomes',
        disabled:false,
        hours:0,
    },
    {
        id:'0018',
        name: 'Georgia da Cruz Pereira',
        disabled:false,
        hours:0,
    },
    {
        id:'0019',
        name: 'Henrique Barbosa Silva',
        disabled:false,
        hours:0,
    },
    {
        id:'0020',
        name: 'Henrique Sergio Lima Pequeno',
        disabled:false,
        hours:0,
    },
    {
        id:'0021',
        name: 'Inga Freire Saboia',
        disabled:false,
        hours:0,
    },
    {
        id:'0022',
        name: 'Ismael Pordeus Bezerra Furtado',
        disabled:false,
        hours:0,
    },
    {
        id:'0023',
        name: 'José Aires de Castro Filho',
        disabled:false,
        hours:0,
    },
    {
        id:'0024',
        name: 'José Gilvan Rodrigues Maia',
        disabled:false,
        hours:0,
    },
    {
        id:'0025',
        name: 'Leonardo Oliveira Moreira',
        disabled:false,
        hours:0,
    },
    {
        id:'0026',
        name: 'Levi Bayde Ribeiro',
        disabled:false,
        hours:0,
    },
    {
        id:'0027',
        name: 'Liandro Roger Memória Machado',
        disabled:false,
        hours:0,
    },
    {
        id:'0028',
        name: 'Luciana de Lima',
        disabled:false,
        hours:0,
    },
    {
        id:'0029',
        name: 'Mara Franklin Bonates',
        disabled:false,
        hours:0,
    },
    {
        id:'0030',
        name: 'Maria de Fátima Costa de Souza',
        disabled:false,
        hours:0,
    },
    {
        id:'0031',
        name: 'Leonília Gabriela Bandeira de Souza',
        disabled:false,
        hours:0,
    },
    {
        id:'0032',
        name: 'Matheus Rodrigo Serafim Rodrigues',
        disabled:false,
        hours:0,
    },
    {
        id:'0033',
        name: 'Mauro Cavalcante Pequeno',
        disabled:false,
        hours:0,
    },
    {
        id:'0034',
        name: 'Natal Anacleto Chicca Junior',
        disabled:false,
        hours:0,
    },
    {
        id:'0035',
        name: 'Neil Armstrong Rezende',
        disabled:false,
        hours:0,
    },
    {
        id:'0036',
        name: 'Priscila Barros David',
        disabled:false,
        hours:0,
    },
    {
        id:'0037',
        name: 'Rafael Augusto Ferreira do Carmo',
        disabled:false,
        hours:0,
    },
    {
        id:'0038',
        name: 'Raquel Santiago Freire',
        disabled:false,
        hours:0,
    },
    {
        id:'0039',
        name: 'Ricardo Brauner dos Santos',
        disabled:false,
        hours:0,
    },
    {
        id:'0040',
        name: 'Robson Carlos Loureiro',
        disabled:false,
        hours:0,
    },
    {
        id:'0041',
        name: 'Ticiana Linhares Coelho da Silva',
        disabled:false,
        hours:0,
    },
    {
        id:'0042',
        name: 'Wellington Wagner Ferreira Sarmento',
        disabled:false,
        hours:0,
    },
    {
        id:'0043',
        name: 'Windson Viana de Carvalho',
        disabled:false,
        hours:0,
    },

]
